export default {
  $schema: 'https://json.schemastore.org/prettierrc',
  printWidth: 120,
  useTabs: false,
  tabWidth: 2,
  singleQuote: true,
  bracketSpacing: true,
  bracketLine: false,
  singleAttributePerLine: true,
  semi: false,
  arrowParens: 'avoid',
  htmlWhitespaceSensitivity: 'ignore',
  trailingComma: 'es5',
  vueIndentScriptAndStyle: false,
}
