export default [
  {
    id: 888,
    parentId: 0,
    component: '',
    path: '/statistics',
    title: '数据总览',
    icon: 'i-statistics',
    redirect: '/statistics/index',
  },
  {
    id: 889,
    parentId: 888,
    component: '/statistics/index',
    path: '/statistics/index',
    title: '数据总览',
    icon: '',
    redirect: '',
  },
  {
    id: 1,
    parentId: 0,
    component: '',
    path: '/user',
    title: '用户',
    icon: 'i-user',
    redirect: '/user/index',
  },
  {
    id: 2,
    parentId: 1,
    component: '/user/list',
    path: '/user/index',
    title: '用户管理',
    icon: '',
    redirect: '',
  },
  {
    id: 3,
    parentId: 1,
    component: '/user/hierarchy',
    path: '/user/hierarchy',
    title: '层级管理',
    icon: '',
    redirect: '',
  },
  {
    id: 4,
    parentId: 0,
    component: '',
    path: '/guild',
    title: '工会管理',
    icon: 'i-guild',
    redirect: '/guild/index',
  },
  {
    id: 5,
    parentId: 4,
    component: '/guild/list',
    path: '/guild/index',
    title: '工会管理',
    icon: '',
    redirect: '',
  },
  {
    id: 6,
    parentId: 0,
    component: '',
    path: '/anchor',
    title: '主播',
    icon: 'i-anchor',
    redirect: '/anchor/index',
  },
  {
    id: 7,
    parentId: 6,
    component: '/anchor/list',
    path: '/anchor/index',
    title: '主播管理',
    icon: '',
    redirect: '',
  },
  {
    id: 8,
    parentId: 6,
    component: '/anchor/detail',
    path: '/anchor/detail',
    title: '编辑主播信息',
    icon: '',
    hide: true,
    redirect: '',
    activeMenu: '/anchor/list',
  },
  {
    id: 9,
    parentId: 6,
    component: '/anchor/statistics',
    path: '/anchor/statistics',
    title: '主播直播数据',
    icon: '',
    redirect: '',
  },
  {
    id: 10,
    parentId: 0,
    component: '',
    path: '/recweight',
    title: '推荐位配置',
    icon: 'icon-menu',
    redirect: '/recweight/index',
  },
  {
    id: 11,
    parentId: 10,
    component: '/recweight/list',
    path: '/recweight/index',
    title: '推荐位配置',
    icon: 'i-recweight',
    redirect: '',
  },
  {
    id: 12,
    parentId: 0,
    component: '',
    path: '/setting',
    title: '平台配置',
    icon: 'i-setting',
    redirect: '/setting/level',
  },
  {
    id: 13,
    parentId: 12,
    component: '/setting/level',
    path: '/setting/level',
    title: '等级配置',
    icon: '',
    redirect: '',
  },
  {
    id: 14,
    parentId: 12,
    component: '/setting/noble',
    path: '/setting/noble',
    title: '贵族配置',
    icon: '',
    redirect: '',
  },
  {
    id: 15,
    parentId: 12,
    component: '/setting/category',
    path: '/setting/category',
    title: '直播分类配置',
    icon: '',
    redirect: '',
  },
  {
    id: 16,
    parentId: 12,
    component: '/setting/client',
    path: '/setting/client',
    title: '版本配置',
    icon: '',
    redirect: '',
  },
  {
    id: 17,
    parentId: 12,
    component: '/setting/general',
    path: '/setting/general',
    title: '综合配置',
    icon: '',
    redirect: '',
  },
  {
    id: 18,
    parentId: 12,
    component: '/setting/redirect',
    path: '/setting/redirect',
    title: '跳转页面配置',
    icon: '',
    redirect: '',
  },
  {
    id: 19999,
    parentId: 0,
    component: '',
    path: '/payment',
    title: '支付管理',
    icon: 'i-payment',
    redirect: '/payment/channel',
  },
  {
    id: 20000,
    parentId: 19999,
    component: '/payment/channel',
    path: '/payment/channel',
    title: '支付渠道',
    icon: '',
    redirect: '',
  },
  {
    id: 20001,
    parentId: 19999,
    component: '/payment/method',
    path: '/payment/method',
    title: '支付方式',
    icon: '',
    redirect: '',
  },
  {
    id: 19,
    parentId: 0,
    component: '',
    path: '/merchant',
    title: '商户管理',
    icon: 'i-merchant',
    redirect: '/merchant/index',
  },
  {
    id: 20,
    parentId: 19,
    component: '/merchant/list',
    path: '/merchant/index',
    title: '商户管理',
    icon: '',
    redirect: '',
  },
  {
    id: 200,
    parentId: 19,
    component: '/merchant/account',
    path: '/merchant/account',
    title: '账户管理',
    icon: '',
    redirect: '',
  },
  {
    id: 21,
    parentId: 0,
    component: '',
    path: '/gift',
    title: '礼物管理',
    icon: 'i-gift',
    redirect: '/gift/index',
  },
  {
    id: 22,
    parentId: 21,
    component: '/gift/list',
    path: '/gift/index',
    title: '礼物管理',
    icon: '',
    redirect: '',
  },
  {
    id: 23,
    parentId: 0,
    component: '',
    path: '/message',
    title: '消息管理',
    icon: 'i-message',
    redirect: '/message/index',
  },
  {
    id: 24,
    parentId: 23,
    component: '/message/list',
    path: '/message/index',
    title: '消息管理',
    icon: '',
    redirect: '',
  },
  {
    id: 255,
    parentId: 0,
    component: '',
    path: '/sms',
    title: '短信管理',
    icon: 'i-sms',
    redirect: '/sms/channel',
  },
  {
    id: 266,
    parentId: 255,
    component: '/sms/channel',
    path: '/sms/channel',
    title: '渠道配置',
    icon: '',
    redirect: '',
  },
  {
    id: 277,
    parentId: 255,
    component: '/sms/template',
    path: '/sms/template',
    title: '模版管理',
    icon: '',
    redirect: '',
  },
  {
    id: 288,
    parentId: 255,
    component: '/sms/record',
    path: '/sms/record',
    title: '短信列表',
    icon: '',
    redirect: '',
  },
  {
    id: 25,
    parentId: 0,
    component: '',
    path: '/notice',
    title: '公告',
    icon: 'i-notice',
    redirect: '/notice/index',
  },
  {
    id: 26,
    parentId: 25,
    component: '/notice/list',
    path: '/notice/index',
    title: '公告管理',
    icon: '',
    redirect: '',
  },
  {
    id: 27,
    parentId: 25,
    component: '/notice/marquee',
    path: '/notice/marquee',
    title: '跑马灯配置',
    icon: '',
    redirect: '',
  },
  {
    id: 28,
    parentId: 0,
    component: '',
    path: '/permissions',
    title: '权限管理',
    icon: 'i-permissions',
    redirect: '/permissions/role',
  },
  {
    id: 29,
    parentId: 28,
    component: '/permissions/role',
    path: '/permissions/role',
    title: '角色管理',
    icon: '',
    redirect: '',
  },
  {
    id: 30,
    parentId: 28,
    component: '/permissions/department',
    path: '/permissions/department',
    title: '部门管理',
    icon: '',
    redirect: '',
  },
  {
    id: 31,
    parentId: 28,
    component: '/permissions/account',
    path: '/permissions/account',
    title: '账号管理',
    icon: '',
    redirect: '',
  },
]
